name: Continuous integration
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint extension
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq dos2unix recode
          bash ./format.sh
